version: "3.7"

services:
    # image project
    app:
        container_name: laravel-docker-test
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-docker-test/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        container_name: laravel-docker-test-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    mysql:
        container_name: laravel-docker-test-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # queue
    queue:
        container_name: laravel-docker-test-queue
        image: laravel-docker-test/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        container_name: laravel-docker-test-redis
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
